# Generated by Django 5.2 on 2025-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=20, verbose_name='Estado de registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subrole',
            field=models.CharField(blank=True, choices=[('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('porteria', 'Portería')], help_text='Especifica el subrol si el usuario es un empleado.', max_length=20, null=True, verbose_name='Subrol (solo empleados)'),
        ),
    ]
