# Generated by Django 5.2 on 2025-05-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_registration_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_completo',
        ),
    ]
