# Generated by Django 5.1.3 on 2025-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designa si este usuario puede autenticarse.', verbose_name='Active user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado de registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subrole',
            field=models.CharField(blank=True, choices=[('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento')], help_text='Especifica el subrol si el usuario es un empleado.', max_length=20, null=True, verbose_name='Subrol (solo empleados)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Nombre de usuario único.', max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
